export const LEVEL_UNKNOWN = 0;
export const LEVEL_NONE = 1;
export const LEVEL_MILD = 2;
export const LEVEL_MODERATE = 3;
export const LEVEL_SEVERE = 4;

const severeFoods = [
  "ACORN SQUASH",
  "MUSSEL",
  "SPAGHETTI SQUASH",
  "TOMATO",
  "WAKAME SEAWEED"
];

const moderateFoods = [
  "AGAVE",
  "ALMOND",
  "AMARANTH",
  "ARROWROOT",
  "BANANA",
  "BISON",
  "BLUEBERRY",
  "BOK CHOY",
  "BREWER'S YEAST",
  "BROCCOLI",
  "CANTALOUPE",
  "CASHEW",
  "CHIA",
  "CLAM",
  "EGG YOLK",
  "FRUCTOSE",
  "HONEY",
  "LIME",
  "MOLASSES",
  "OYSTER",
  "SAFFLOWER",
  "SALMON",
  "SARDINE",
  "SCALLION",
  "SHRIMP",
  "SORGHUM",
  "STEVIA LEAF",
  "STRAWBERRY",
  "SUGAR",
  "SWEET POTATO",
  "SWISS CHARD",
  "TILAPIA",
  "WHEAT"
];

const mildFoods = [
  "ADZUKI BEANS",
  "ALLSPICE",
  "APPLE",
  "ARTICHOKE",
  "ARUGULA",
  "ASPARAGUS",
  "AVOCADO",
  "BAKER'S YEAST",
  "BEEF",
  "BLACK CURRANT",
  "BLACK PEPPER",
  "BLACK-EYED PEA",
  "BRAZIL NUT",
  "CARDAMOM",
  "CAROB",
  "CHAMOMILE",
  "CODFISH",
  "CORIANDER SEED",
  "CUMIN",
  "DANDELION LEAF",
  "DATE",
  "ENDIVE",
  "FLOUNDER",
  "GINGER",
  "GRAPEFRUIT",
  "GREEN TEA",
  "GROUPER",
  "HEMP",
  "HORSERADISH",
  "JICAMA",
  "LYCHEE",
  "MAHI MAHI",
  "MILK",
  "MUNG BEAN",
  "NUTRITIONAL YEAST",
  "OKRA",
  "OREGANO",
  "PINTO BEAN",
  "PORK",
  "RED PALM FRUIT",
  "SAGE",
  "SEA BASS",
  "SHIITAKE MUSHRM",
  "SNAPPER (RED)",
  "SOLE",
  "SOYBEAN",
  "SPEARMINT",
  "SPELT",
  "SPINACH",
  "STRING BEAN",
  "SUNFLOWER",
  "TANGERINE",
  "TROUT",
  "TUNA",
  "TURNIP",
  "VANILLA",
  "VEAL",
  "VENISON",
  "WALNUT",
  "WHITE POTATO",
  "WILD RICE",
  "YELLOW SQUASH",
  "ZUCCHINI SQUASH",
]

const noneFoods = [
  "BELL PEPPER MIX",
  "BUTTERNUT SQUASH",
  "CARROT",
  "CHICORY",
  "ESCAROLE",
  "HABANERO PEPPER",
  "KELP",
  "LENTIL BEAN",
  "ONION",
  "RED BEET / SUGAR",
  "SHALLOTS",
  "YAM",
  "BLACK BEANS",
  "BUTTON MUSHROOM",
  "CAULIFLOWER",
  "COLLARD GREENS",
  "FAVA BEAN",
  "ICEBERG LETTUCE",
  "KIDNEY BEAN",
  "LIMA BEAN",
  "PARSNIP",
  "RHUBARB",
  "TARO ROOT",
  "YELLOW PEA",
  "BOSTON BIBB LETTU",
  "CABBAGE",
  "CELERY",
  "CUCUMBER",
  "FENNEL SEED",
  "JALAPEÑO PEPP",
  "LEAF LETT (RED/GR",
  "MUSTARD GREENS",
  "PORTOBELLO MUSHRM",
  "ROMAINE LETT",
  "WATER CHESTNUT",
  "BRSSLS SPROUT",
  "CANNELLINI BEANS",
  "CHICKPEA",
  "EGGPLANT",
  "GREEN PEA",
  "KALE",
  "LEEK",
  "NAVY BEAN",
  "RADISH",
  "RUTABAGA",
  "WATERCRESS",
  "APRICOT",
  "CRANBERRY",
  "GUAVA",
  "LEMON",
  "OLIVE",
  "PEAR",
  "PLUM",
  "STAR FRUIT",
  "BLACKBERRY",
  "DRAGON FRUIT",
  "HONEYDEW MLN",
  "MANGO",
  "ORANGE",
  "PERSIMMON",
  "POMEGRANATE",
  "WATERMELON",
  "CAPERS",
  "FIG",
  "JACKFRUIT",
  "MULBERRY",
  "PAPAYA",
  "PINEAPPLE",
  "PUMPKIN",
  "CHERRY",
  "GRAPE",
  "KIWI",
  "NECTARINE",
  "PEACH",
  "PLANTAIN",
  "RASPBERRY",
  "CHICKEN",
  "TURKEY",
  "CHICKEN LIVER",
  "DUCK",
  "LAMB",
  "ANCHOVY",
  "HALIBUT",
  "SWORDFISH",
  "CATFISH",
  "LOBSTER",
  "CRAB",
  "MACKEREL",
  "HADDOCK",
  "SCALLOP",
  "BARLEY",
  "MILLET",
  "RYE",
  "BUCKWHEAT",
  "OAT (GLUTEN FREE)",
  "TAPIOCA",
  "CORN",
  "QUINOA",
  "TEFF",
  "MALT",
  "RICE (BRWN/WHT)",
  "ANCHO CHILI PEPP",
  "CHIVES",
  "CURRY",
  "PAPRIKA",
  "SAFFRON",
  "BASIL",
  "CILANTRO",
  "DILL",
  "PARSLEY",
  "TARRAGON",
  "BAY LEAF",
  "CINNAMON",
  "LICORICE",
  "PEPPERMINT",
  "THYME",
  "CAYENNE PEPPER",
  "CLOVE",
  "NUTMEG",
  "ROSEMARY",
  "TURMERIC",
  "BLACK TEA",
  "COCONUT",
  "HAZELNUT",
  "PEANUT",
  "POPPY SEED",
  "CANOLA (RAPESEED)",
  "COFFEE",
  "HOPS",
  "PECAN",
  "SESAME",
  "CARAWAY",
  "FLAXSEED",
  "MACADAMIA",
  "PINE NUT",
  "COCOA",
  "GARLIC",
  "MUSTARD SEED",
  "PISTACHIO",
]

const severeAdditives = [];

const moderateAdditives = [
  "ACID RED #14",
  "BHA",
  "BLUE#2 INDIGO CARMINE",
  "GREEN#3 FAST GREEN",
  "ACETAMINOPHEN",
  "AMOXICILLIN",
  "DIFLUNISAL",
  "FUSARIUM OXYSPORUM",
  "SPONDYLOCLADIUM",
  "TRICHODERMA",
];

const mildAdditives = [
  "ACID BLUE #3",
  "ANNATTO",
  "BENZOIC ACID",
  "BHT",
  "BLUE#1 BRILLIANT BLUE",
  "BRILLIANT BLACK",
  "MSG",
  "RED#4 CARMINE",
  "XYLITOL",
  "YELLOW#5 TARTRAZINE",
  "AMPICILLIN",
  "ASPIRIN",
  "IBUPROFEN",
  "KETOPROFEN",
  "PIROXICAM",
  "CURV SPECIFERA",
  "PENICILLIUM",
  "BETA-CAROTENE",
  "LECITHIN",
  "RED#2 AMARANTH",
];

const noneAdditives = [
  "ASPARTAME",
  "ORRIS ROOT",
  "SODIUM SULFITE",
  "CITRIC ACID",
  "POLYSORBATE 80",
  "SORBIC ACID",
  "ERYTHRITOL",
  "RED#40 ALLURA RED",
  "SUCRALOSE",
  "HIGH FRUCTOSE CORN SYRUP",
  "SACCHARIN",
  "YELLOW#6",
  "DICLOFENAC",
  "NEOMYCIN",
  "STREPTOMYCIN",
  "GENTAMICIN",
  "NYSTATIN",
  "SULFAMETHOXAZOLE",
  "INDOMETHACIN",
  "PENICILLAMINE",
  "SULINDAC",
  "NAPROXEN",
  "PENICILLIN",
  "TETRACYCLINE",
  "ASPERGILLUS",
  "EPICOCCUM NIGRUM",
  "MONILIA SITOPHILA",
  "RHIZOPUS NIGRICAN",
  "BOTRYTIS",
  "GEOTRICHUM",
  "MUCOR RACEMOSUS",
  "RHODOTORULA",
  "RUBRA",
  "CEPHALOSPORIUM",
  "HELMINTHOSPORIUM",
  "PHOMA HERBARUM",
  "CLADO HERBARUM",
  "HORMODENDRUM",
  "PULLULARIA",
  "RED#3",
  "ERYTHROSINE",
];

const severeIngredients = severeFoods.concat(severeAdditives);
const moderateIngredients = moderateFoods.concat(moderateAdditives);
const mildIngredients = mildFoods.concat(mildAdditives);
const noneIngredients = noneFoods.concat(noneAdditives);

export const ingredientLevels = [
  {level: LEVEL_UNKNOWN, ingredients: []},
  {level: LEVEL_NONE, ingredients: noneIngredients.sort()},
  {level: LEVEL_MILD, ingredients: mildIngredients.sort()},
  {level: LEVEL_MODERATE, ingredients: moderateIngredients.sort()},
  {level: LEVEL_SEVERE, ingredients: severeIngredients.sort()},
];
